# This is a basic workflow to help you get started with Actions

name: line the pipe.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k3s-time:
    runs-on: ubuntu-20.04
    steps:
      - name: install k3s
        run: |
          curl -sfL https://get.k3s.io | sh -
      
      - name: set kubeconfig
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: sudo mkdir ~/.kube && sudo cp ${KUBECONFIG} ~/.kube/config
      
      - name: test
        run: |
          sleep 10
          sudo kubectl get nodes
          sudo kubectl get pod -A
