# This is a basic workflow to help you get started with Actions

name: line the pipe.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k3s-time:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        uses: debianmaster/actions-k3s@v1.0.0
        with:
          version: v1.0.0

      # Runs a set of commands using the runners shell
      - name: run k3s
        run: |
          k3s kubectl get node --write-kubeconfig-mode
