# This is a basic workflow to help you get started with Actions

name: line the pipe.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  node-time:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        id: noders
      - run: |
          npm init -f
          npm install express
          ls -al
          pwd
